
services:
  postgres:
    image: postgis/postgis
    networks:
      - server_network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    networks:
        - server_network
    command: npm run start:dev
    env_file: ./.env.development
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/opt/node/app:delegated
      - ./package.json:/opt/node/package.json
      - ./package-lock.json:/opt/node/package-lock.json
      - notused:/opt/node/app/node_modules
volumes:
  postgres_data:
  notused:
networks:
  server_network: